# File: docker/docker-compose.cpu.yml

services:
  api:
    image: llm-api-cpu
    container_name: llm-api-cpu-container
    build:
      context: ..
      dockerfile: docker/Dockerfile.cpu
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../adapters:/app/adapters