# File: docker/docker-compose.gpu.yml

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.gpu
    image: llm-api-gpu
    container_name: llm-api-gpu-container
    ports:
      - "8000:8000"
    volumes:
      - ../adapters/finetuned-qwen-lora:/app/adapters
    environment:
      - HF_HOME=/app/cache
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
